### ISSUE TITLE
Unable to install HTSeq

### ISSUE THREAD

**Issue by ronghai-li** [htseq/htseq#87]
**Software versions**
Specify what versions of the following you are using:
- operating system 
Darwin lironghaideMacBook-Pro.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112 arm64
- `Python` 3.10.8
- `numpy` 2.0.0
- `pysam` 0.22.1
- `Cython` 3.0.10
- `SWIG` 4.2.1
- `pip` 24.1.1
- `bitarray` 2.9.2

**Describe the bug**
Unable to install HTSeq.
Cython had an error compiling the .pyx file for HTSeq.

I've tried the methods suggested in the community so far and still can't get it to install properly, specifically.
1. I first tried `pip install HTSeq` and received the following error
```
~ % pip install HTSeq      
Collecting HTSeq
  Using cached htseq-2.0.7.tar.gz (466 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in ./anaconda3/lib/python3.10/site-packages (from HTSeq) (1.23.5)
Requirement already satisfied: pysam in ./anaconda3/lib/python3.10/site-packages (from HTSeq) (0.22.1)
Building wheels for collected packages: HTSeq
  Building wheel for HTSeq (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for HTSeq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      running bdist_wheel
      running build
      running build_py
      running preprocess
      Cython version 3.0.10
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                          self.seq[i * characters_per_line: (i + 1) * characters_per_line].decode() + "\n")
                      i += 1
      
          cpdef object add_bases_to_count_array(Sequence self, numpy.ndarray count_array_):
      
              cdef numpy.ndarray[numpy.int_t, ndim = 2] count_array = count_array_
                                       ^
      ------------------------------------------------------------
      
      src/HTSeq/_HTSeq.pyx:1171:33: Invalid type.
      Traceback (most recent call last):
        File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 171, in <module>
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "<string>", line 157, in run
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/private/var/folders/n0/f4r5wgwj0kvbkwtj_n4m50m40000gn/T/pip-build-env-sybfnro5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "<string>", line 109, in run
        File "<string>", line 131, in swig_and_cython
        File "<string>", line 117, in c
        File "/Users/lironghai/anaconda3/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'cython -3 src/HTSeq/_HTSeq.pyx -o src/_HTSeq.c' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for HTSeq
Failed to build HTSeq
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (HTSeq)
```
2. I also tried downloading the source package from the HTSeq PyPI page, unpack the tarball, go into the directory with the unpacked files and type there：`python setup.py build`，and received the following error：
```
htseq-2.0.7 % python setup.py build
fatal: not a git repository (or any of the parent directories): .git
/Users/lironghai/anaconda3/lib/python3.10/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running build
running build_py
running preprocess
Cython version 3.0.10

Error compiling Cython file:
------------------------------------------------------------
...
                    self.seq[i * characters_per_line: (i + 1) * characters_per_line].decode() + "\n")
                i += 1

    cpdef object add_bases_to_count_array(Sequence self, numpy.ndarray count_array_):

        cdef numpy.ndarray[numpy.int_t, ndim = 2] count_array = count_array_
                                 ^
------------------------------------------------------------

src/HTSeq/_HTSeq.pyx:1171:33: Invalid type.
Traceback (most recent call last):
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/htseq-2.0.7/setup.py", line 171, in <module>
    setup(name='HTSeq',
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 976, in run_command
    super().run_command(command)
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 976, in run_command
    super().run_command(command)
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/htseq-2.0.7/setup.py", line 157, in run
    self.run_command('preprocess')
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 976, in run_command
    super().run_command(command)
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/htseq-2.0.7/setup.py", line 109, in run
    self.swig_and_cython()
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/htseq-2.0.7/setup.py", line 131, in swig_and_cython
    c(cython+' -3 src/HTSeq/_HTSeq.pyx -o src/_HTSeq.c')
  File "/Users/lironghai/anaconda3/lib/python3.10/site-packages/htseq-2.0.7/setup.py", line 117, in c
    def c(x): return check_call(x, shell=True)
  File "/Users/lironghai/anaconda3/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cython -3 src/HTSeq/_HTSeq.pyx -o src/_HTSeq.c' returned non-zero exit status 1.
```
I would be grateful if you could assist me.

**Comment by iosonofabio** [comment]
There was a recent change on the main branch that I'll release tomorrow, I'll ask you to try then

**Comment by ronghai-li** [comment]
Now I can install it successfully via `pip install HTSeq`, so thanks for all your contributions to this package!
```
(For_sc) lironghai@lironghaideMacBook-Pro ~ % pip show HTseq      
Name: HTSeq
Version: 2.0.8
Summary: A framework to process and analyze data from high-throughput sequencing (HTS) assays
Home-page: https://github.com/htseq
Author: Simon Anders, Fabio Zanini
Author-email: fabio.zanini@unsw.edu.au
License: GPL3
Location: /Users/lironghai/anaconda3/envs/For_sc/lib/python3.10/site-packages
Requires: numpy, pysam
Required-by: biofluff
```

**Comment by iosonofabio** [comment]
No problem, remember to cite our 2022 paper if you publish 😊
